export enum CreateTokenResponse {
  MISSING_MEDIA = "MISSING_MEDIA",
  MISSING_THUMBNAIL = "MISSING_THUMBNAIL",
  MISSING_TITLE = "MISSING_TITLE",
  MISSING_COLLECTION = "MISSING_COLLECTION",
  SIGN_TRANSACTION = "SIGN_TRANSACTION",
  TOKEN_CREATED = "TOKEN_CREATED",
}
