export enum CreateTokenResponse {
  MISSING_IMAGE = "MISSING_IMAGE",
  MISSING_THUMBNAIL = "MISSING_THUMBNAIL",
  MISSING_TITLE = "MISSING_TITLE",
  MISSING_COLLECTION = "MISSING_COLLECTION",
  SIGN_TRANSACTION = "SIGN_TRANSACTION",
}
